/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v202004010832.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_EXAMPLES_E01_Hello_World_DBUS_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_EXAMPLES_E01_Hello_World_DBUS_STUB_ADAPTER_HPP_

#include <v0/commonapi/examples/E01HelloWorldStub.hpp>
#include "v0/commonapi/examples/E01HelloWorldDBusDeployment.hpp"

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0 {
namespace commonapi {
namespace examples {

template <typename _Stub = ::v0::commonapi::examples::E01HelloWorldStub, typename... _Stubs>
class E01HelloWorldDBusStubAdapterInternal
    : public virtual E01HelloWorldStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> E01HelloWorldDBusStubAdapterHelper;

    ~E01HelloWorldDBusStubAdapterInternal() {
        deactivateManagedInstances();
        E01HelloWorldDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return E01HelloWorld::getInterface();
    }

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v0::commonapi::examples::E01HelloWorldStub,
        CommonAPI::Version
        > getE01HelloWorldInterfaceVersionStubDispatcher;

    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v0::commonapi::examples::E01HelloWorldStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::DBus::StringDeployment>,
        std::tuple< CommonAPI::DBus::StringDeployment>
    
        > sayHelloStubDispatcher;

    E01HelloWorldDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      E01HelloWorldDBusStubAdapterHelper(_address, _connection, false, _stub) {
        E01HelloWorldDBusStubAdapterHelper::addStubDispatcher({ "sayHello", "s" }, &sayHelloStubDispatcher);
        E01HelloWorldDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getE01HelloWorldInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"sayHello\">\n"
            "<arg name=\"_name\" type=\"s\" direction=\"in\" />\n"
            "<arg name=\"_message\" type=\"s\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v0::commonapi::examples::E01HelloWorldStub,
    CommonAPI::Version
    > E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>::getE01HelloWorldInterfaceVersionStubDispatcher(&E01HelloWorldStub::lockInterfaceVersionAttribute, &E01HelloWorldStub::getInterfaceVersion, "uu");


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v0::commonapi::examples::E01HelloWorldStub,
    std::tuple< std::string>,
    std::tuple< std::string>,
    std::tuple< CommonAPI::DBus::StringDeployment>,
    std::tuple< CommonAPI::DBus::StringDeployment>

    > E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>::sayHelloStubDispatcher(
    &E01HelloWorldStub::sayHello, "s",
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)));


template <typename _Stub = ::v0::commonapi::examples::E01HelloWorldStub, typename... _Stubs>
class E01HelloWorldDBusStubAdapter
    : public E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< E01HelloWorldDBusStubAdapter<_Stub, _Stubs...>> {
public:
    E01HelloWorldDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          E01HelloWorldDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace examples
} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_EXAMPLES_E01_Hello_World_DBUS_STUB_ADAPTER_HPP_
